//
//  StudyGuide.swift
//  CramForRounds
//

import Foundation

struct StudyGuide: Codable, Identifiable {
    let id: UUID
    let originalCase: String
    let generatedContent: String
    let timestamp: Date

    init(id: UUID = UUID(), originalCase: String, generatedContent: String, timestamp: Date = Date()) {
        self.id = id
        self.originalCase = originalCase
        self.generatedContent = generatedContent
        self.timestamp = timestamp
    }

    /// Export the entire session as markdown
    func exportAsMarkdown(with messages: [Message]) -> String {
        var markdown = """
        # Cram For Rounds - Study Session

        **Generated:** \(timestamp.formatted(date: .long, time: .shortened))

        ---

        ## Original Case

        \(originalCase)

        ---

        ## Study Guide

        \(generatedContent)

        ---

        ## Practice Rounds Session

        """

        for message in messages {
            switch message.role {
            case .user:
                markdown += "\n**You:** \(message.content)\n"
            case .assistant:
                markdown += "\n**Doc Pixel:** \(message.content)\n"
            case .system:
                markdown += "\n*\(message.content)*\n"
            }
        }

        markdown += "\n\n---\n\n*Generated by Cram For Rounds iOS App*\n"

        return markdown
    }
}
